version: "3"
services:
  backend:
    image: node:20.4.0 # Use an official Node.js image
    container_name: backend
    working_dir: /app
    volumes:
      - ./:/app # Map your Node.js app directory
    networks:
      - mongodb
    ports:
      - "3000:3000" # Map host port to container port
    environment:
      MONGODB_URI: mongodb://mongodb:27017/wfsoccer
    command: npm run start:dev
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest # Use an official MongoDB image
    container_name: mongodb
    networks:
      - mongodb
    ports:
      - "27017:27017" # Map host port to container port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword

networks:
  mongodb:
    driver: bridge
